### ISSUE TITLE
Players:Get return 500 error

### ISSUE THREAD

**Issue by bensoncho** [playgameservices/android-basic-samples#255] opened 2017-08-10 02:10 UTC
I used APIs Explorer. 
Url is https://developers.google.com/games/services/web/api/players/get?hl=zh-TW
And request parameters：playerId => me
Then I got response： { "error": { "code": 500, "message": null } }
api url： https://www.googleapis.com/games/v1/players/me?key={YOUR_API_KEY}
Now why I can't get player id ? 
thanks

**Comment by mwgray** [comment] 2018-01-03 23:21
Was not able to reproduce.  Closing.

**Closed by mwgray** 2018-01-03 23:21 UTC
