### ISSUE TITLE
GameHelper.isSignedIn() doesnt work properly

### ISSUE THREAD

**Issue by B4dT0bi** [playgameservices/android-basic-samples#149] opened 2015-08-01 10:29 UTC
When you sign in to Google Play Services and open the Leaderboard and logout from Google Play Services from there the GameHelper.isSignedIn still returns true because it is only checking if mGoogleApiClient is not null and if it is connected.

In my code I first check GameHelper.isSignedIn and if this returns true I call the Leaderboards Intent with
startActivityForResult(Games.Leaderboards.getLeaderboardIntent(gameHelper.getApiClient(), code), 100);

and this gets an Exception : 
java.lang.SecurityException: Not signed in when calling API
            at android.os.Parcel.readException(Parcel.java:1546)
            at android.os.Parcel.readException(Parcel.java:1499)
            at com.google.android.gms.games.internal.IGamesService$Stub$Proxy.zzv(Unknown Source)
            at com.google.android.gms.games.internal.GamesClientImpl.zzo(Unknown Source)
            at com.google.android.gms.games.internal.api.LeaderboardsImpl.getLeaderboardIntent(Unknown Source)
            at com.google.android.gms.games.internal.api.LeaderboardsImpl.getLeaderboardIntent(Unknown Source)
            at de.badtobi.game.samegame.android.AndroidLauncher.showLeaderboard(AndroidLauncher.java:363)

So I think the isSignedIn method should also check if a user is really signed in.

regards Tobi

**Comment by ianhanniballake** [comment] 2015-08-01 17:52
Duplicate of #121

**Comment by claywilkinson** [comment] 2015-08-04 21:46
GameHelper has outlived its usefulness.  If you look at the samples, it is no longer used.  An informative, and slightly humorous video was made detailing the changes:  [Death of BasegameActivity](https://www.youtube.com/watch?v=1oSoaFLuTwM).  Do you have the same issue with one of the samples?  If not, maybe migrating your app to manage the client in the same manner is the solution.

**Closed** 2016-12-21 22:13 UTC
